exclude: '^docs/source/conf.py'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-case-conflict
    -   id: check-vcs-permalinks
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
# Python formatters
-   repo: local
    hooks:
      - id: black
        name: Black (python formatter)
        entry: poetry run black src/ tests/
        language: system
        types: [python]
        require_serial: true
-   repo: local
    hooks:
      - id: isort
        name: isort (python import sorter)
        entry: poetry run isort
        language: system
        types: [python]
        require_serial: true
# Build script linters
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
    -   id: shellcheck
        name: Shellcheck
        args: ["-f", "gcc"]  # output filename:linenum:colnum (clickable)
-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.0
    hooks:
      - id: docker-compose-check
        name: Docker-compose.yaml validity
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ["--tee", "--output-file", "test_results/flake8_report.txt"]
        additional_dependencies:
          - "flake8-bandit==2.1.2"
          - "flake8-bugbear==21.3.2"
          - "flake8-docstrings==1.6.0"
