exclude: '^docs/source/conf.py'
repos:
# # SEE WORDLE.ORG for FIXME explaining why manual export is prettier (damn Emacs!)
# -   repo: local
#     hooks:
#     -   id: emacs-tangle
#         name: Emacs tangle org-mode literate-programming files (ensures code synced)
#         entry: make tangle-code
#         language: system
#         files: wordle.org
#         pass_filenames: false
# -   repo: local
#     hooks:
#     -   id: emacs-export-html
#         name: Emacs export org-mode file to static HTML
#         entry: make wordle.html
#         language: system
#         files: wordle.org
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-case-conflict
    -   id: check-vcs-permalinks
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
# Python formatters
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
##Build script linters
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    -   id: mypy
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ["--tee", "--output-file", "test_results/flake8_report.txt"]
        additional_dependencies:
          - "flake8-bandit==2.1.2"
          - "flake8-bugbear==22.1.11"
          - "flake8-docstrings==1.6.0"
